### ISSUE TITLE
record RMC status information

### ISSUE THREAD

**Issue by bumi** [GreatLakesEnergy/sesh-api-helper#13]
to better monitor the RMCs we want to record their status requests and track the status and IP of it. 
This allows us to get notified when an RMC is down. 

First step is store status information in a MySQL table. That information includes: 
- ip
- date
-

**Comment by jlark** [comment]
I think
- IP
- Date/time
- signal strength
- airtime balance
- Node signal strength
- errors/exceptions occuring?

**Comment by bumi** [comment]
sounds good! do you have an example payload? 

re exceptions: we could try to push those directly to the exception tracking tool.

**Comment by jlark** [comment]
Currently it's only IP address that I have, as full GSM integration is still in the works.

I'm unsure of how wise sending exceptions of the air would be. (Again,bandwith is very expensive our here)

I 'll look at this tomorrow but it should be quite trivial. I'll construct it so that it's similar to a normal datapacket. This way we can simply re-use one of the mapping endpoints, with a mapping in the configuration.

**Comment by bumi** [comment]
If we can define the format I'd prefer a simple key-value structure represented in a format like JSON.
For saving some bytes we could try [MessagePack](http://msgpack.org/). (there libraries for 50+ languages, incl. arduino) 
or maybe some other binary format? - I also saw some mentioning of [google protocol buffers for embedded devices](https://code.google.com/archive/p/nanopb/)... - not really sure about the size-efficiency of those formats.

**Comment by bumi** [comment]
which I guess is what you have been mentioning in #14 
somehow I still think using plain gzip is a good, easy start. 
if we prepare some payload examples I can run it through different options to compare the request size.

**Comment by bumi** [comment]
btw. the IP address should also be accessible through `request.remote_addr` which we can store when a data request comes in.

**Comment by bumi** [comment]
any thoughts?

**Comment by jlark** [comment]
Hi Bumi,
Sorry for the radio silence.  I haven't had the chance to code on the RMC too much as we just got a new intern and I've been focusing him on the dashboard and doing cleanup( writing tests that I neglected to write that have finally caught up with  me!)
- Enabling GZIP is still on my todo. It's enabled on nginx side needs to be enabled on RMC side
- I'm currently working on getting signal strength , wlan ipadress on the RMC.

Packet can  look like
{ 'ip':<wlan_ip_address>,
  'signal_strength':<0-100 number>
  'up-time':<seconds>,
}

PB and Message pack a very interesting.

**Comment by bumi** [comment]
OK, I will add an endpoint that accepts a flat JSON http body and stores it in a MySQL table. What is the name of that table? or should it be configurable? 

The JSON should also contain the unit id. (still mixing those up... site_id, node, unit, ... :/ )

**Comment by jlark** [comment]
No, need for node ID as this will represent the whole site. so it will have the API_KEY which we can use to map back to site_id.

I think it's best to have a defualt table like RMC_Status that can be overwritten with a configuration.

**Comment by bumi** [comment]
started in #17

**Comment by bumi** [comment]
how do we proceed here?

**Comment by jlark** [comment]
Ok, Let me try to sum up the discussion to make. The problem with the RMC status table is that a lot of the information that can be sent from the RMC can actually be deduced from the normal data packages sent. Since bandwith is expense we should do the bare minimum and deduce the rest from elsewhere.

Given this I think the best option right now is to have an endpoint that the RMC will do a GET request on periodically. No data will be sent.

On Kraken it will simply store the IP, API_KEY, DATE_TIME, bytes_recieved in a status table.  Kraken can have an internal cache where it will store/accumulate  `content-length` from each RMC and will append it to the status table when the GET request to the status endpoint is sent.

I think this will use the least bandwith and give us the most amount of useful information from each unit.

**Comment by jlark** [comment]
Re: signal strength, I think it's highly redundent to constantly send this as and ideally we would only send this information if there is a change to it. Perhaps the RMC will only send this across if there is change in the value.

**Comment by bumi** [comment]
OK.
so we have the status endpoint that you can send an empty POST request to and it will store the account and the time of last contact. Can you add an IP field to the table and I will add the IP address.

there is no need to store the API KEY as we better store the table ID as a foreign key. 

I will change the other insert endpoints that they also write an status entry with the last contact.

**Comment by bumi** [comment]
I don't really like calculating the content-length, as I still don't see the usefulness in that. 
If that data shall be used for verifying the data consumption and what the carriers charge us, then we should not use knowingly wrong data for the calculation (the content-lenght is just not enough to do that)

**Comment by jlark** [comment]
Ok, We could turn this around then. The only true way to see the data sent is see what's going through the adapter, as this is what the ISP will be charging us for. I don't want to send this data periodically but it's already readily available on the RMC.

I can implement an endpoint on the RMC that will respond with certain meta information if someone asks for it. (signal strength, uptime, data_sent)

**Comment by jlark** [comment]
I think then we can completely remove the status endpoint and simply have populate a status table with IP and datetime of last transmission. This data is available in the normal request so like you said we can populate the table from bulk post.

**Comment by bumi** [comment]
but why then the status table at all? we simply can add the IP to the data entry (what do we need the IP for again? :)

**Comment by jlark** [comment]
haha going in circles. IP address is needed in case we need to ssh into the RMC unit. Mainly for debugging a system remotely

We could add the ip address to the data entry, however we'll be moving away from a table based store (mysql) to a column based one(influx) more rapidly. The ip-address we'll always want it in a table based store , so that's why I want a status table : )

**Comment by bumi** [comment]
sorry for driving us in circles. 
here is a PR: #22
