### ISSUE TITLE
Unified logging

### ISSUE THREAD

**Issue by jlark** [GreatLakesEnergy/sesh-api-helper#33]
I'm going to take the side of not writing any code this time and suggest we use paper trail.

**Comment by bumi** [comment]
it is easy to change since we will try to simply send syslog to papertrail. 
need to see how to log to syslog with flask, and we need to see how we can use remote syslog on azure. 
will look into it.

**Comment by jlark** [comment]
hmmm syslog? Won't that be too much noise?

**Comment by bumi** [comment]
no because filtering is super simple.
you look at entries only from kraken for example.
or kraken and mysql - but only warnings or above, etc.

On Monday, May 16, 2016, Alp Tilev notifications@github.com wrote:

> hmmm syslog? Won't that be too much noise?
> 
> —
> You are receiving this because you were assigned.
> Reply to this email directly or view it on GitHub
> https://github.com/GreatLakesEnergy/sesh-api-helper/issues/33#issuecomment-219430389

## 

Michael Bumann

F       +49 (0) 176 22747893
E       hello@michaelbumann.com
T       twitter.com/bumi
